### ISSUE TITLE
Capstone version compatibility

### ISSUE THREAD

**Issue by patacca** [quarkslab/qbindiff#37]
After merging #36 we will break compatibility with older versions of capstone. We should identify which version is the first one that is compatible with qbindiff and enforce it in pyproject.toml

**Comment by RobinDavid** [comment]
I just checked. Its the very latest: ``5.0.1``.

Previous versions don't have ``wasm_const`` or the enum value ``arm64_const.ARM64_OP_SVCR`` which were apparently introduced in the latest.

**Comment by patacca** [comment]
This has been now enforced.
